services:
  # サービスタイプを「Webサービス」として定義
  - type: web
    name: yuzutube-search-nodejs
    # ビルドに使う環境（Node.js）を指定
    env: node
    # ビルドコマンド（依存関係のインストール）
    buildCommand: npm install
    # 起動コマンド（server.jsを実行）
    startCommand: node server.js
    # 環境変数 $PORT を Render が自動で設定し、server.jsでそれを受け取ります。
    # server.jsのPORT設定（process.env.PORT || 3000）に対応しています。
    envVars:
      - key: NODE_VERSION
        value: 20
